import { NextRequest, NextResponse } from "next/server";
import {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  AlignmentType, BorderStyle,
} from "docx";

export async function POST(req: NextRequest) {
  try {
    const { title, transcript, channel } = await req.json();
    if (!transcript) {
      return NextResponse.json({ error: "Transcript is required" }, { status: 400 });
    }

    const doc = new Document({
      title: title || "Lecture Notes",
      creator: "Tube Lecture Buddy",
      description: `Transcript for: ${title}`,
      sections: [
        {
          properties: {},
          children: [
            // Title
            new Paragraph({
              heading: HeadingLevel.TITLE,
              alignment: AlignmentType.CENTER,
              spacing: { after: 200 },
              children: [
                new TextRun({
                  text: title || "Lecture Notes",
                  bold: true,
                  size: 56,
                  color: "6C5CE7",
                  font: "Arial",
                }),
              ],
            }),
            // Channel
            new Paragraph({
              alignment: AlignmentType.CENTER,
              spacing: { after: 400 },
              children: [
                new TextRun({
                  text: `Channel: ${channel || "Unknown"}`,
                  size: 28,
                  color: "888888",
                  font: "Arial",
                }),
              ],
            }),
            // Separator
            new Paragraph({
              border: {
                bottom: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
              },
              spacing: { after: 400 },
              children: [],
            }),
            // Transcript heading
            new Paragraph({
              heading: HeadingLevel.HEADING_1,
              spacing: { before: 200, after: 200 },
              children: [
                new TextRun({
                  text: "📝 Full Transcript",
                  bold: true,
                  size: 36,
                  font: "Arial",
                }),
              ],
            }),
            // Transcript content - split into paragraphs
            ...transcript
              .split(/(?<=[.!?])\s+/)
              .reduce((acc: string[], sentence: string, i: number) => {
                const idx = Math.floor(i / 5);
                if (!acc[idx]) acc[idx] = "";
                acc[idx] += sentence + " ";
                return acc;
              }, [])
              .map(
                (para: string) =>
                  new Paragraph({
                    spacing: { after: 200 },
                    children: [
                      new TextRun({
                        text: para.trim(),
                        size: 24,
                        font: "Arial",
                      }),
                    ],
                  })
              ),
            // Footer
            new Paragraph({
              border: {
                top: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
              },
              spacing: { before: 600 },
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({
                  text: "Generated by Tube Lecture Buddy",
                  size: 20,
                  color: "AAAAAA",
                  italics: true,
                  font: "Arial",
                }),
              ],
            }),
          ],
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);

    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${(title || "lecture").replace(/[^a-zA-Z0-9]/g, "_")}_transcript.docx"`,
      },
    });
  } catch (error) {
    console.error("DOCX generation error:", error);
    return NextResponse.json({ error: "Failed to generate DOCX" }, { status: 500 });
  }
}
