import { NextRequest, NextResponse } from "next/server";
import PptxGenJS from "pptxgenjs";

interface Topic {
  id: number;
  timestamp: string;
  endTimestamp: string;
  title: string;
  keywords: string[];
  summary: string;
}

interface FrameData {
  timestamp: number;
  image: string | null; // base64
}

interface TranscriptItem {
  text: string;
  offset: number;
  duration: number;
}

function getSegmentText(items: TranscriptItem[], startTs: string, endTs: string): string {
  const toMs = (ts: string) => {
    const parts = ts.split(":").map(Number);
    if (parts.length === 3) return (parts[0] * 3600 + parts[1] * 60 + parts[2]) * 1000;
    return (parts[0] * 60 + parts[1]) * 1000;
  };
  const startMs = toMs(startTs);
  const endMs = toMs(endTs);
  return items
    .filter((i) => i.offset >= startMs && i.offset < endMs)
    .map((i) => i.text)
    .join(" ");
}

function extractBullets(text: string, max = 5): string[] {
  const sentences = text.split(/(?<=[.!?])\s+/).filter((s) => s.length > 15 && s.length < 200);
  if (sentences.length <= max) return sentences;
  const step = Math.floor(sentences.length / max);
  const out: string[] = [];
  for (let i = 0; i < sentences.length && out.length < max; i += step) out.push(sentences[i]);
  return out;
}

export async function POST(req: NextRequest) {
  try {
    const { title, channel, topics, transcript, frames } = await req.json();
    if (!topics || !transcript) {
      return NextResponse.json({ error: "Topics and transcript required" }, { status: 400 });
    }

    const pptx = new PptxGenJS();
    pptx.layout = "LAYOUT_WIDE";
    pptx.author = "Tube Lecture Buddy";

    const topicsList: Topic[] = topics;
    const transcriptItems: TranscriptItem[] = transcript;
    const framesList: FrameData[] = frames || [];

    // Build a lookup: timestamp(seconds) -> base64 image
    const frameLookup: Record<number, string> = {};
    for (const f of framesList) {
      if (f.image) frameLookup[f.timestamp] = f.image;
    }

    // ===== TITLE SLIDE =====
    const s1 = pptx.addSlide();
    s1.background = { fill: "0F0E17" };
    s1.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 13.33, h: 0.08, fill: { color: "6C5CE7" } });
    s1.addText(title || "Lecture Notes", {
      x: 1, y: 1.8, w: 11.33, h: 1.8,
      fontSize: 36, fontFace: "Arial", color: "FFFFFF", bold: true, align: "center",
    });
    s1.addText(channel ? `📺 ${channel}` : "", {
      x: 1, y: 3.8, w: 11.33, h: 0.6,
      fontSize: 16, fontFace: "Arial", color: "A29BFE", align: "center",
    });
    s1.addText("Study Material • Generated by Tube Lecture Buddy", {
      x: 1, y: 5.5, w: 11.33, h: 0.4,
      fontSize: 11, fontFace: "Arial", color: "6C6E8A", align: "center", italic: true,
    });

    // ===== TABLE OF CONTENTS =====
    const toc = pptx.addSlide();
    toc.background = { fill: "0F0E17" };
    toc.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 13.33, h: 0.08, fill: { color: "6C5CE7" } });
    toc.addText("📋 Table of Contents", {
      x: 0.8, y: 0.4, w: 11.73, h: 0.8,
      fontSize: 28, fontFace: "Arial", color: "FFFFFF", bold: true,
    });
    const tocItems = topicsList.map((t) => ({
      text: `${t.timestamp}  —  ${t.title}`,
      options: { fontSize: 13, fontFace: "Arial", color: "E0E0E0" as string, bullet: { code: "25B6", color: "6C5CE7" as string }, lineSpacingMultiple: 1.7, paraSpaceBefore: 3 },
    }));
    toc.addText(tocItems, { x: 1.2, y: 1.5, w: 10.93, h: 5.5, valign: "top" });

    // ===== TOPIC SLIDES WITH FRAMES =====
    for (const topic of topicsList) {
      const slide = pptx.addSlide();
      slide.background = { fill: "0F0E17" };
      slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 13.33, h: 0.06, fill: { color: "6C5CE7" } });

      // Timestamp badge + slide number
      slide.addText(`⏱ ${topic.timestamp} - ${topic.endTimestamp}`, {
        x: 0.5, y: 0.2, w: 3, h: 0.35, fontSize: 9, fontFace: "Arial", color: "A29BFE",
      });
      slide.addText(`${topic.id} / ${topicsList.length}`, {
        x: 10, y: 0.2, w: 2.83, h: 0.35, fontSize: 9, fontFace: "Arial", color: "6C6E8A", align: "right",
      });

      // Topic title
      slide.addText(topic.title, {
        x: 0.5, y: 0.6, w: 12.33, h: 0.7,
        fontSize: 22, fontFace: "Arial", color: "FFFFFF", bold: true,
      });

      // Divider
      slide.addShape(pptx.ShapeType.rect, { x: 0.5, y: 1.35, w: 2.5, h: 0.03, fill: { color: "6C5CE7" } });

      // Keywords
      if (topic.keywords.length > 0) {
        slide.addText(`🏷 ${topic.keywords.join("  •  ")}`, {
          x: 0.5, y: 1.5, w: 12.33, h: 0.3, fontSize: 9, fontFace: "Arial", color: "A29BFE", italic: true,
        });
      }

      // Check if we have a frame for this topic
      const topicTs = topic.timestamp.split(":").map(Number);
      const topicSec = topicTs.length === 3 ? topicTs[0] * 3600 + topicTs[1] * 60 + topicTs[2] : topicTs[0] * 60 + topicTs[1];
      const frameBase64 = frameLookup[topicSec];

      const segmentText = getSegmentText(transcriptItems, topic.timestamp, topic.endTimestamp);
      const bullets = extractBullets(segmentText);

      if (frameBase64) {
        // Layout: Frame on left, bullet points on right
        slide.addImage({
          data: `image/jpeg;base64,${frameBase64}`,
          x: 0.5, y: 1.9, w: 5.8, h: 3.26,
          rounding: true,
        });

        if (bullets.length > 0) {
          const bulletItems = bullets.map((b) => ({
            text: b.length > 120 ? b.slice(0, 120) + "..." : b,
            options: { fontSize: 11, fontFace: "Arial", color: "D0D0D0" as string, bullet: { code: "25CF", color: "6C5CE7" as string }, lineSpacingMultiple: 1.4, paraSpaceBefore: 4 },
          }));
          slide.addText(bulletItems, { x: 6.6, y: 1.9, w: 6.23, h: 4.8, valign: "top" });
        }
      } else {
        // No frame - full width bullet points
        if (bullets.length > 0) {
          const bulletItems = bullets.map((b) => ({
            text: b,
            options: { fontSize: 13, fontFace: "Arial", color: "D0D0D0" as string, bullet: { code: "25CF", color: "6C5CE7" as string }, lineSpacingMultiple: 1.5, paraSpaceBefore: 5 },
          }));
          slide.addText(bulletItems, { x: 0.7, y: 1.9, w: 11.93, h: 4.8, valign: "top" });
        } else {
          slide.addText(segmentText.slice(0, 900), {
            x: 0.7, y: 1.9, w: 11.93, h: 4.8,
            fontSize: 13, fontFace: "Arial", color: "D0D0D0", lineSpacingMultiple: 1.4, valign: "top",
          });
        }
      }
    }

    // ===== SUMMARY SLIDE =====
    const sum = pptx.addSlide();
    sum.background = { fill: "0F0E17" };
    sum.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 13.33, h: 0.08, fill: { color: "6C5CE7" } });
    sum.addText("📌 Summary", {
      x: 1, y: 1.2, w: 11.33, h: 0.8,
      fontSize: 32, fontFace: "Arial", color: "FFFFFF", bold: true, align: "center",
    });
    sum.addText(
      `This lecture covered ${topicsList.length} topics.\n\n${topicsList.map((t) => `• ${t.title}`).join("\n")}`,
      { x: 1, y: 2.2, w: 11.33, h: 4.5, fontSize: 13, fontFace: "Arial", color: "D0D0D0", lineSpacingMultiple: 1.4, valign: "top", align: "center" }
    );
    sum.addText("Generated by Tube Lecture Buddy 🎓", {
      x: 1, y: 6.8, w: 11.33, h: 0.3, fontSize: 10, fontFace: "Arial", color: "6C6E8A", align: "center", italic: true,
    });

    const buffer = (await pptx.write({ outputType: "nodebuffer" })) as Buffer;

    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "Content-Disposition": `attachment; filename="${(title || "lecture").replace(/[^a-zA-Z0-9]/g, "_")}_study_material.pptx"`,
      },
    });
  } catch (error) {
    console.error("PPT generation error:", error);
    return NextResponse.json({ error: "Failed to generate PPT" }, { status: 500 });
  }
}
